set_route:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: mtviki_matrix
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: mtviki_matrix
    input:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 16
          mode: box
    outputs:
      required: true
      example: "[1, 3] or 'all'"
      selector:
        object:

save_scene:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: mtviki_matrix
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: mtviki_matrix
    scene:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 16
          mode: box

recall_scene:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: mtviki_matrix
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: mtviki_matrix
    scene:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 16
          mode: box

set_output_hdcp:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: mtviki_matrix
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: mtviki_matrix
    output:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 16
          mode: box
    mode:
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 3
          mode: box

set_input_edid:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: mtviki_matrix
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: mtviki_matrix
    input:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 16
          mode: box
    edid:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 16
          mode: box

locate:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: mtviki_matrix
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: mtviki_matrix
    count:
      required: false
      default: 4
      selector:
        number:
          min: 1
          max: 20
          mode: box
    interval:
      required: false
      default: 0.35
      selector:
        number:
          min: 0.1
          max: 2.0
          step: 0.05
          unit_of_measurement: s
          mode: box
